package types

const (
	UnitOfMeasureA     string = "A"
	UnitOfMeasureASU   string = "ASU"
	UnitOfMeasureC     string = "C"
	UnitOfMeasureDB    string = "dB"
	UnitOfMeasureDeg   string = "Deg"
	UnitOfMeasureF     string = "F"
	UnitOfMeasureG     string = "G"
	UnitOfMeasureHz    string = "Hz"
	UnitOfMeasureKPa   string = "kPa"
	UnitOfMeasureKvar  string = "kvar"
	UnitOfMeasureKvarh string = "kvarh"
	UnitOfMeasureKW    string = "kW"
	UnitOfMeasureKWh   string = "kWh"
	UnitOfMeasureLx    string = "lx"
	UnitOfMeasureMs2   string = "ms2"
	UnitOfMeasureN     string = "N"
	UnitOfMeasureOhm   string = "ohm"
	UnitOfMeasurePct   string = "pct"
	UnitOfMeasureRH    string = "RH"
	UnitOfMeasureRPM   string = "RPM"
	UnitOfMeasureS     string = "s"
	UnitOfMeasureVar   string = "var"
	UnitOfMeasureVarh  string = "varh"
	UnitOfMeasureV     string = "V"
	UnitOfMeasureW     string = "W"
	UnitOfMeasureWh    string = "Wh"
)
