package types

const (
	ConnectorTypeCccs1           string = "cCCS1"
	ConnectorTypeCccs2           string = "cCCS2"
	ConnectorTypeCg105           string = "cG105"
	ConnectorTypeCtesla          string = "cTesla"
	ConnectorTypeCtype1          string = "cType1"
	ConnectorTypeCtype2          string = "cType2"
	ConnectorTypeS3091P16A       string = "S309-1P-16A"
	ConnectorTypeS3091P32A       string = "S309-1P-32A"
	ConnectorTypeS3093P16A       string = "S309-3P-16A"
	ConnectorTypeS3093P32A       string = "S309-3P-32A"
	ConnectorTypeSbs1361         string = "sBS1361"
	ConnectorTypeScee77          string = "sCEE-7-7"
	ConnectorTypeStype2          string = "sType2"
	ConnectorTypeStype3          string = "sType3"
	ConnectorTypeOther1PhMax16A  string = "Other1PhMax16A"
	ConnectorTypeOther1PhOver16A string = "Other1PhOver16A"
	ConnectorTypeOther3Ph        string = "Other3Ph"
	ConnectorTypeWInductive      string = "wInductive"
	ConnectorTypeWResonant       string = "wResonant"
	ConnectorTypeUndetermined    string = "Undetermined"
	ConnectorTypeUnknown         string = "Unknown"
)
